enum PdaScannerOperationCode {
  SET_BROADCAST_ACTION,
  SET_BROADCAST_DATA_TAG,
  ADD_BROADCAST_DATA_TAG,
  START_LISTENER_BROADCAST,
  STOP_LISTENER_BROADCAST,
  LISTENER_BROADCAST,
  DISPOSE_OVER,
  ERROR_CODE,
}